{
 "title": "IoT App Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Door Button 1",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door button 1\")"
    }
   ]
  },
  {
   "title": "Door Buzzer 1",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Buzzer 1\")"
    }
   ]
  },
  {
   "title": "Door LED 1",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door LED 1\")"
    }
   ]
  },
  {
   "title": "Door Membrane Switch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Membrane Switch\")"
    }
   ]
  },
  {
   "title": "Door Motion Sensor 1",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Motion Sensor 1\")"
    }
   ]
  },
  {
   "title": "Door Distance Sensor 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Distance Sensor 1\")"
    }
   ]
  },
  {
   "title": "Door Button 2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door button 2\")"
    }
   ]
  },
  {
   "title": "Kitchen Button",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Kitchen Button\")"
    }
   ]
  },
  {
   "title": "Door Motion Sensor 2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Motion Sensor 2\")"
    }
   ]
  },
  {
   "title": "Door Distance Sensor 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Door Distance Sensor 2\")"
    }
   ]
  },
  {
   "title": "Kitchen DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Temperature Kitchen\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Humidity Kitchen\")"
    }
   ]
  },
  {
   "title": "Kitchen 4-Digit 7-Segment Display",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Kitchen Segment Display\")"
    }
   ]
  },
  {
   "title": "Gyroscope",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Accelerometer X\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Accelerometer Y\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Accelerometer Z\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Gyroscope X\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Gyroscope Y\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Gyroscope Z\")"
    }
   ]
  },
  {
   "title": "Bedroom DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Temperature Bedroom\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Humidity Bedroom\")"
    }
   ]
  },
  {
   "title": "Master Bedroom DHT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Temperature Master Bedroom\")"
    },
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Humidity Master Bedroom\")"
    }
   ]
  },
  {
   "title": "Living Room Motion Sensor",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Living Room Motion Sensor\")"
    }
   ]
  },
  {
   "title": "Living Room Display",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Living Room Display\")"
    }
   ]
  },
  {
   "title": "Bedroom RGB",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Bedroom RGB\")"
    }
   ]
  },
  {
   "title": "Bedroom IR",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"Bedroom IR\")"
    }
   ]
  },
  {
   "title": "Alarm Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -24h)\n|> filter(fn: (r) => r._measurement == \"Alarm Event\")\n|> sort(columns: [\"_time\"], desc: true)\n|> limit(n: 50)"
    }
   ]
  },
  {
   "title": "People Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n|> range(start: -10m)\n|> filter(fn: (r) => r._measurement == \"People Count\")"
    }
   ]
  }
 ]
}